Run e2e somoke test in CI

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -44,6 +44,36 @@ jobs:
             dashgit-web/test/actual
             dashgit-web/test/mochawesome-report
 
+  test-e2e:
+    runs-on: ubuntu-latest
+    # As in test-ut: avoids duplicate execution of pr from local repo, but allows pr from forked repos and dependabot
+    #if: ${{ false }}
+    if: (github.event_name != 'pull_request' && ! github.event.pull_request.head.repo.fork) || (github.event_name == 'pull_request' && (github.event.pull_request.head.repo.fork || startsWith(github.head_ref, 'dependabot/')))
+    steps:
+      - name: Checkout GitHub repo
+        uses: actions/checkout@v7
+      - name: Use Node.js
+        uses: actions/setup-node@v6
+        with:
+          node-version: '18.x'
+      - name: Install dependencies
+        working-directory: ./dashgit-web/e2e
+        run: npm install
+      - name: Install Playwright browser
+        working-directory: ./dashgit-web/e2e
+        run: npx playwright install --with-deps chromium
+      - name: Run e2e smoke tests
+        working-directory: ./dashgit-web/e2e
+        run: npm test
+      - name: Publish Playwright report
+        if: success() || failure() # always run even if the previous step fails
+        uses: actions/upload-artifact@v7.0.1
+        with:
+          name: "test-e2e-report-files"
+          path: |
+            dashgit-web/e2e/playwright-report
+            dashgit-web/e2e/test-results
+
   sonarqube:
     # As in test-ut, but excludes dependabot updates to remove duplicates on local prs
     #if: ${{ false }}
